Repository UMC-Plantory/iOS, pull requests merged in 2025-08, with the labels that each got.

#12 feat: 테라리움 UI
  Plantory/Plantory.xcodeproj/project.pbxproj
  Plantory/Plantory/Assets.xcassets/Chat/Contents.json
  Plantory/Plantory/Assets.xcassets/Chat/chat_logo.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Chat/chat_logo.imageset/chat_logo.pdf
  Plantory/Plantory/Assets.xcassets/Chat/send_button.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Chat/send_button.imageset/send_button.pdf
  Plantory/Plantory/Assets.xcassets/Dot Menu.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Dot Menu.imageset/Dot Menu.pdf
  Plantory/Plantory/Assets.xcassets/Login/Contents.json
  Plantory/Plantory/Assets.xcassets/Login/apple_login.imageset/Contents 2.json
  Plantory/Plantory/Assets.xcassets/Login/apple_login.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Login/apple_login.imageset/apple_login.pdf
  Plantory/Plantory/Assets.xcassets/Login/kakao_login.imageset/Contents 2.json
  Plantory/Plantory/Assets.xcassets/Login/kakao_login.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Login/kakao_login.imageset/kakao_login.pdf
  Plantory/Plantory/Assets.xcassets/Login/logo.imageset/Contents 2.json
  Plantory/Plantory/Assets.xcassets/Login/logo.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Login/logo.imageset/logo.png
  Plantory/Plantory/Assets.xcassets/Terrarium/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/GreenBackground.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/GreenBackground.imageset/greenground.pdf
  Plantory/Plantory/Assets.xcassets/Terrarium/Level01.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/Level01.imageset/level1.pdf
  Plantory/Plantory/Assets.xcassets/Terrarium/PlantBackground.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/PlantBackground.imageset/PlantBackground.pdf
  Plantory/Plantory/Assets.xcassets/Terrarium/Rose.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/Rose.imageset/Rose.pdf
  Plantory/Plantory/Assets.xcassets/Terrarium/TerrariumGuideBottom.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/TerrariumGuideBottom.imageset/TerrariumGuideBottom.pdf
  Plantory/Plantory/Assets.xcassets/Terrarium/TerrariumGuideMiddle.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/TerrariumGuideMiddle.imageset/TerrariumGuideMiddle.pdf
  Plantory/Plantory/Assets.xcassets/Terrarium/TerrariumGuideTop.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/TerrariumGuideTop.imageset/TerrariumGuideTop.pdf
  Plantory/Plantory/Assets.xcassets/Terrarium/Watering.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/Watering.imageset/watering.pdf
  Plantory/Plantory/Assets.xcassets/Terrarium/face_angry.imageset/Asset 4@2x.pdf
  Plantory/Plantory/Assets.xcassets/Terrarium/face_angry.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/gauge_background.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/gauge_background.imageset/gauge_background.pdf
  Plantory/Plantory/Assets.xcassets/Terrarium/tutorial.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/Terrarium/tutorial.imageset/tutorial.pdf
  Plantory/Plantory/Common/Enum/Terrarium/TerrariumTab.swift
  Plantory/Plantory/Models/DTO/Terrarium/TerrariumModel.swift
  Plantory/Plantory/Models/Terrarium/EmotionStat.swift
  Plantory/Plantory/Models/Terrarium/PlantPopupModel.swift
  Plantory/Plantory/Resource/Font/Fonts.swift
  Plantory/Plantory/Service/MoyaRouter/TerrariumAPI.swift
  Plantory/Plantory/Service/MoyaRouter/TerrariumRouter.swift
  Plantory/Plantory/ViewModels/Terrarium/TerrariumViewModel.swift
  Plantory/Plantory/Views/BaseTabView.swift
  Plantory/Plantory/Views/Login/PermitView.swift
  Plantory/Plantory/Views/Terrarium/CustomSegmentView.swift
  Plantory/Plantory/Views/Terrarium/FlowerCompleteView.swift
  Plantory/Plantory/Views/Terrarium/GradientBox.swift
  Plantory/Plantory/Views/Terrarium/MyGardenContent.swift
  Plantory/Plantory/Views/Terrarium/PlantPopupView.swift
  Plantory/Plantory/Views/Terrarium/ProgressGaugeView.swift
  Plantory/Plantory/Views/Terrarium/TerrariumPopup.swift
  Plantory/Plantory/Views/Terrarium/TerrariumView.swift
Labels: ✨ FEAT, ♻️ REFACTOR

#13 feat: 일기 작성 페이지 UI
  Plantory/Plantory.xcodeproj/project.pbxproj
  Plantory/Plantory/Assets.xcassets/gradient_circle.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/gradient_circle.imageset/Ellipse 67.pdf
  Plantory/Plantory/Assets.xcassets/happy_tapped.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/happy_tapped.imageset/Frame 143.pdf
  Plantory/Plantory/Assets.xcassets/happy_untapped.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/happy_untapped.imageset/Frame 143-6.pdf
  Plantory/Plantory/Assets.xcassets/mad_tapped.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/mad_tapped.imageset/Frame 143-2.pdf
  Plantory/Plantory/Assets.xcassets/mad_untapped.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/mad_untapped.imageset/Frame 143-8.pdf
  Plantory/Plantory/Assets.xcassets/normal_tapped.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/normal_tapped.imageset/Frame 143-4.pdf
  Plantory/Plantory/Assets.xcassets/normal_untapped.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/normal_untapped.imageset/Frame 143-9.pdf
  Plantory/Plantory/Assets.xcassets/photo.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/photo.imageset/humbleicons_image.svg
  Plantory/Plantory/Assets.xcassets/sad_tapped.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/sad_tapped.imageset/Frame 143-2.pdf
  Plantory/Plantory/Assets.xcassets/sad_untapped.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/sad_untapped.imageset/Frame 143-7.pdf
  Plantory/Plantory/Assets.xcassets/sprout.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/sprout.imageset/Group 32.pdf
  Plantory/Plantory/Assets.xcassets/surprised_tapped.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/surprised_tapped.imageset/Frame 143-5.pdf
  Plantory/Plantory/Assets.xcassets/surprised_untapped.imageset/Contents.json
  Plantory/Plantory/Assets.xcassets/surprised_untapped.imageset/Frame 143-10.pdf
  Plantory/Plantory/Common/UIComponents/LongPressedEmotionButton.swift
  Plantory/Plantory/Resources/Colors.xcassets/diarybackground.colorset/Contents.json
  Plantory/Plantory/Resources/Colors.xcassets/diaryfont.colorset/Contents.json
  Plantory/Plantory/ViewModels/Home/StepIndicatorViewModel.swift
  Plantory/Plantory/Views/BaseTabView.swift
  Plantory/Plantory/Views/Home/AddDiary/AddDiaryView.swift
  Plantory/Plantory/Views/Home/AddDiary/CompletedView.swift
  Plantory/Plantory/Views/Home/AddDiary/DatePickerView.swift
  Plantory/Plantory/Views/Home/AddDiary/DiaryStepView.swift
  Plantory/Plantory/Views/Home/AddDiary/EmotionStepView.swift
  Plantory/Plantory/Views/Home/AddDiary/PhotoStepView.swift
  Plantory/Plantory/Views/Home/AddDiary/SleepStepView.swift
  Plantory/Plantory/Views/Home/AddDiary/Step.swift
Labels: ✨ FEAT, ♻️ REFACTOR

#27 feat: HomeView API 연결, 날짜 선택 모달 수정
  Plantory/Plantory.xcodeproj/project.pbxproj
  Plantory/Plantory/Common/Enum/Home/EmotionColors.swift
  Plantory/Plantory/Models/DTO/Home/HomeDTO.swift
  Plantory/Plantory/Models/Domain/Home/HomeModel.swift
  Plantory/Plantory/Models/Domain/Home/MonthYearPick.swift
  Plantory/Plantory/Resource/Assets/Colors.xcassets/happy.colorset/Contents.json
  Plantory/Plantory/Resource/Assets/Colors.xcassets/mad.colorset/Contents.json
  Plantory/Plantory/Resource/Assets/Colors.xcassets/sad.colorset/Contents.json
  Plantory/Plantory/Resource/Assets/Colors.xcassets/soso.colorset/Contents.json
  Plantory/Plantory/Service/MoyaRouter/HomeRouter.swift
  Plantory/Plantory/Service/MoyaService/HomeService.swift
  Plantory/Plantory/Service/UseCaseService.swift
  Plantory/Plantory/ViewModels/Home/CalendarEntry.swift
  Plantory/Plantory/ViewModels/Home/DiaryStore.swift
  Plantory/Plantory/ViewModels/Home/HomeViewModel.swift
  Plantory/Plantory/Views/BaseTabView.swift
  Plantory/Plantory/Views/Home/CalendarView.swift
  Plantory/Plantory/Views/Home/DetailSheetView.swift
  Plantory/Plantory/Views/Home/HomeView.swift
  Plantory/Plantory/Views/Home/MonthYearhPickerView.swift
  Plantory/Plantory/Views/Home/MyProgressView.swift
Labels: 🐛 BUG, ✨ FEAT

#29 feat: DiaryList API 연결
  Plantory/Plantory/Common/Enum/DiaryList/Emotion.swift
  Plantory/Plantory/Core/Navigation/NavigationDestination.swift
  Plantory/Plantory/Core/Navigation/NavigationRoutingView.swift
  Plantory/Plantory/Models/DTO/Diary/DiaryDTO.swift
  Plantory/Plantory/Models/DiaryList/DiaryListModel.swift
  Plantory/Plantory/Service/MoyaRouter/DiaryRouter.swift
  Plantory/Plantory/Service/MoyaService/ChatService.swift
  Plantory/Plantory/Service/MoyaService/DiaryService.swift
  Plantory/Plantory/Service/UseCaseService.swift
  Plantory/Plantory/ViewModels/DiaryList/CheckViewModel.swift
  Plantory/Plantory/ViewModels/DiaryList/DiaryFilterViewModel.swift
  Plantory/Plantory/ViewModels/DiaryList/DiaryListViewModel.swift
  Plantory/Plantory/ViewModels/DiaryList/SearchViewModel.swift
  Plantory/Plantory/Views/BaseTabView.swift
  Plantory/Plantory/Views/Diary/DeleteConfirmationSheet.swift
  Plantory/Plantory/Views/Diary/DiaryCheckView.swift
  Plantory/Plantory/Views/Diary/DiaryFilterView.swift
  Plantory/Plantory/Views/Diary/DiaryListView.swift
  Plantory/Plantory/Views/Diary/DiaryRowView.swift
  Plantory/Plantory/Views/Diary/FilterComponentView.swift
  Plantory/Plantory/Views/Diary/SearchView.swift
Labels: ✨ FEAT
